package CalculatorApp;


/**
* CalculatorApp/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* środa, 23 listopada 2016 23:53:54 CET
*/

public interface CalculatorOperations 
{
  int add(int a, int b);
  int multiply(int a, int b);
  int subtract(int a, int b);
  int divide(int a, int b);
  void shutdown();
} // interface CalculatorOperations
